// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuWPBmUPR0vdG7xWTRoFIvotHxYd6fBtc',
    appId: '1:972572328026:android:bf91a3155850b79e121863',
    messagingSenderId: '972572328026',
    projectId: 'smart-mirror-capstone-53e65',
    storageBucket: 'smart-mirror-capstone-53e65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYTgBsKePZmrgGzj9xp9jRPHtMpM3sorA',
    appId: '1:972572328026:ios:ac72399439c48567121863',
    messagingSenderId: '972572328026',
    projectId: 'smart-mirror-capstone-53e65',
    storageBucket: 'smart-mirror-capstone-53e65.firebasestorage.app',
    iosBundleId: 'com.smartmirror.smartMirrorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6TR88vmmnfhuQ50Qcwm3dpwtMpCJtfo8',
    appId: '1:972572328026:web:1be23b0134c6bb42121863',
    messagingSenderId: '972572328026',
    projectId: 'smart-mirror-capstone-53e65',
    authDomain: 'smart-mirror-capstone-53e65.firebaseapp.com',
    storageBucket: 'smart-mirror-capstone-53e65.firebasestorage.app',
  );
}